name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Build ic10lsp
        working-directory: ./anex-ic10/ic10lsp
        run: cargo build --release

      - name: Copy ic10lsp binary
        run: |
          mkdir -p ./anex-ic10/anex-ic10-language-support/bin
          cp ./anex-ic10/ic10lsp/target/release/ic10lsp ./anex-ic10/anex-ic10-language-support/bin/ic10lsp

      - name: Install Dependencies
        working-directory: ./anex-ic10/anex-ic10-language-support
        run: npm ci

      - name: Package VSCode extension
        working-directory: ./anex-ic10/anex-ic10-language-support
        run: npx vsce package

      - name: Get version from package.json
        id: package-version
        working-directory: ./anex-ic10/anex-ic10-language-support
        run: |
          VERSION=$(jq -r .version package.json)
          echo "::set-output name=version::$VERSION"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          files: |
            ./anex-ic10/anex-ic10-language-support/*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to VS Marketplace
        working-directory: ./anex-ic10/anex-ic10-language-support
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}